### ISSUE TITLE
Asset cache

### ISSUE THREAD

**Issue by rudy1976s** [mirko-pagliai/assets#21]
I mirko
I noticed that compressed css does not apply any cache rules as cake php Html helper normally does.
is there a way to add add cache expiration and LastModified?

Thank you Rudy

In Italian:
ciao Mirko
c'è un modoper aggiungere la gestione della cache lato browser ? Con l'helper di cake mettendo asset su force viene generato il timestamp e il lastmodified. C'è modo di passarelo anche all'Asset Helper?

Grazie

Rudy

**Comment by mirko-pagliai** [comment]
Hello @rudy1976s 

I don't understand exactly what you're talking about.

Can you post some code about "what are you doing" and "what you expect"?

**Comment by rudy1976s** [comment]
Hi  Mirko
I need to speed up a bit my page and I decided to add the possibility of using browser cache to speed up asset load.
I have setup your plugin and created a minified css files: when using cake HTML Helper for assets there is the option to add a timestamp to it and to add a cache header setting "LastModified" to the response.
I noticed that minified files dos not have such cache header.

![schermata 2017-11-22 alle 15 54 09](https://user-images.githubusercontent.com/1161343/33133549-6e821bca-cf9d-11e7-872c-1fef8937ae99.png)

Thank you

Rudy

**Comment by mirko-pagliai** [comment]
Okay, maybe I understand.
If I understand correctly, there is no helper, but the controller that "provides" the asset.

**Comment by rudy1976s** [comment]
Yes there should be the a way to be able to add headers for cache and other stuffs if needed.

Thanks

Rudy

**Comment by mirko-pagliai** [comment]
Yes.

Probably this:
https://book.cakephp.org/3.0/en/controllers/request-response.html#interacting-with-browser-caching

I'll see what I can do

**Comment by rudy1976s** [comment]
Yes  thats it .

**Comment by mirko-pagliai** [comment]
Hello @rudy1976s 

I changed the [timestamp](https://github.com/mirko-pagliai/assets/tree/timestamp) branch. Now the timestamp is attached to the assets, if required by the application configuration (`Asset.timestamp`).

So, try to install the `timestamp` branch:
    composer require mirko-pagliai/assets:dev-timestamp

And remember to configure your app (`bootstrap.php`), as indicated in the [Cookbook](https://book.cakephp.org/3.0/en/development/configuration.html#general-configuration): 

    Configure::write('Asset.timestamp', true);

Let me know if this change is fine. Then I'll see for the rest.

**Comment by mirko-pagliai** [comment]
In the same branch there is also a change that sends the `Last-Modified` header to the client.

Let me know if both changes are fine.

**Comment by mirko-pagliai** [comment]
released new version
