### ISSUE TITLE
Setting false debug crashes all

### ISSUE THREAD

**Issue by rudy1976s** [mirko-pagliai/assets#22]
Hi I have set up debug to false and the site is no longer able to load anything while turning back to debug true, it works fine.

Rudy

Italian

Ciao
ho configurato tutto per bene e in debug funziona prfettamente mentre non appena tolgo il debug si sfascia tutto, non carica  nulla dando  500 senza però descritto il tipo di errore.
Hai qualche idea?

Grazie

RUdy

**Comment by mirko-pagliai** [comment]
Please, see log files

**Comment by rudy1976s** [comment]
Sorry my mistake : )

**Comment by mirko-pagliai** [comment]
What was the problem?  
However, it's normal that if you disable debugging, you will not see the error in the video. This is the normal behavior of CakePHP.

**Comment by rudy1976s** [comment]
Because I have make a mistake putting Cache::consume while the static function does not have a consume function !
It was only a coincidence that after installing and configuring your great plugin I have introduced such a bug ; I apologize for the inconvenience .
Now works fine ,
Thank you  Grazie
