### ISSUE TITLE
Add asyncronous asset loading

### ISSUE THREAD

**Issue by rudy1976s** [mirko-pagliai/assets#23]
This is not a bug but a possible enhancement.

It will be great to be able to have the possibility of loading the compressed script asyncronously , to avoid the "above the fold" problem .
Actually when rendering the view there is time wasted waiting for the script to load completely.

Another alternative way could be the possibility of rendering the minified file directly instead of link a file, adding a parameter to the helper.
This would probably solve the "above the fold" issue.

Could you add this feature ?

Thank you

Rudy

**Comment by mirko-pagliai** [comment]
> Actually when rendering the view there is time wasted waiting for the script to load completely.

Unfortunately, this is the disadvantage of this system: the time needed to dynamically process assets.
I don't think it is possible to do much. On the other hand, if the goal is to have less time, it is better to use static assets.

> Another alternative way could be the possibility of rendering the minified file directly instead of link a file, adding a parameter to the helper.

I don't think anyway it would change anything. However, the file is essential to have a sort of cached copy. To render directly the file, however, it should be read entirely.

The goal you want to achieve can only be done through static assets, which are updated manually by you.
Obviously, you will lose the ability to dynamically generate them and, as mentioned above, you will have to manage them manually.

For the asyncronous asset loading, look something [like this](https://github.com/filamentgroup/loadCSS).
