### ISSUE TITLE
Asset paths

### ISSUE THREAD

**Issue by rudy1976s** [mirko-pagliai/assets#24]
noticed that using the plugin I need to completely rewrite the internal path of the asset resources: does it is a normal behavior?
Assets which normally refers to some images inside their css are no longer able to map those paths.

example from a fontello css :  src: url('../font/fontello.eot?89024372#iefix') format('embedded-opentype'),

The fontello is no longer able to retrieve its font because the path is not found: solution is reference it with absolute path, but getting problems afterwards with updates and maintainability.

**Comment by mirko-pagliai** [comment]
This may be normal.
Where is the `font` directory?
And in what directory are the assets generated?
Have you tried to generate assets in the `webroot/assets` directory (by default they are generated in the `tmp/assets` directory)?
